# Main background, accents and key color
theme[main_bg]="#{{colors.surface.default.hex_stripped}}"
theme[main_fg]="#{{colors.on_surface.default.hex_stripped}}"
theme[title]="#{{colors.on_surface.default.hex_stripped}}"
theme[hi_fg]="#{{colors.primary.default.hex_stripped}}"
theme[selected_bg]="#{{colors.surface_container_highest.default.hex_stripped}}"
theme[selected_fg]="#{{colors.primary.default.hex_stripped}}"
theme[inactive_fg]="#{{colors.outline.default.hex_stripped}}"
theme[graph_text]="#{{colors.on_surface_variant.default.hex_stripped}}"

# Text color for box borders
theme[proc_box]="#{{colors.primary.default.hex_stripped}}"
theme[cpu_box]="#{{colors.secondary.default.hex_stripped}}"
theme[mem_box]="#{{colors.tertiary.default.hex_stripped}}"
theme[net_box]="#{{colors.primary.default.hex_stripped}}"

# Outline color of boxes
theme[proc_border]="#{{colors.outline.default.hex_stripped}}"
theme[cpu_border]="#{{colors.outline.default.hex_stripped}}"
theme[mem_border]="#{{colors.outline.default.hex_stripped}}"
theme[net_border]="#{{colors.outline.default.hex_stripped}}"

# CPU graph colors
theme[cpu_start]="#{{colors.primary.default.hex_stripped}}"
theme[cpu_mid]="#{{colors.secondary.default.hex_stripped}}"
theme[cpu_end]="#{{colors.tertiary.default.hex_stripped}}"

# Mem box outline color
theme[free]="#{{colors.primary.default.hex_stripped}}"
theme[cached]="#{{colors.secondary.default.hex_stripped}}"
theme[available]="#{{colors.tertiary.default.hex_stripped}}"
theme[used]="#{{colors.error.default.hex_stripped}}"

# Download/Upload graph colors
theme[download_start]="#{{colors.primary.default.hex_stripped}}"
theme[download_mid]="#{{colors.secondary.default.hex_stripped}}"
theme[download_end]="#{{colors.tertiary.default.hex_stripped}}"
theme[upload_start]="#{{colors.tertiary.default.hex_stripped}}"
theme[upload_mid]="#{{colors.secondary.default.hex_stripped}}"
theme[upload_end]="#{{colors.primary.default.hex_stripped}}"
