[theme]
background = "{{colors.surface.default.hex}}"
primary = "{{colors.primary.default.hex}}"
secondary = "{{colors.secondary.default.hex}}"
title = "{{colors.on_surface.default.hex}}"
playing = "{{colors.primary.default.hex}}"
playing_selected = "{{colors.on_surface.default.hex}}"
playing_bg = "{{colors.surface_container_high.default.hex}}"
highlight = "{{colors.on_surface.default.hex}}"
highlight_bg = "{{colors.surface_container_high.default.hex}}"
error = "{{colors.error.default.hex}}"
error_bg = "{{colors.error_container.default.hex}}"
statusbar = "{{colors.on_surface.default.hex}}"
statusbar_bg = "{{colors.surface_container.default.hex}}"
statusbar_progress = "{{colors.primary.default.hex}}"
cmdline = "{{colors.on_surface.default.hex}}"
cmdline_bg = "{{colors.surface.default.hex}}"
