---
dotfiles_packages_fedora:
  - git
  - bash
  - fastfetch
  - niri
  - waybar
  - alacritty
  - fuzzel
  - cava
  - btop
  - matugen
  - swaybg
  - swaylock
  - playerctl
  - brightnessctl
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-pulseaudio
  - wireplumber
  - neovim
  - xpad
  - orca
  - cascadia-code-nf-fonts
  - jetbrains-mono-fonts
  - papirus-icon-theme
  - breeze-cursor-theme

dotfiles_packages_arch:
  - git
  - bash
  - fastfetch
  - niri
  - waybar
  - alacritty
  - fuzzel
  - cava
  - btop
  - matugen
  - swaybg
  - swaylock
  - playerctl
  - brightnessctl
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber
  - neovim
  - xpad
  - orca
  - ttf-cascadia-code-nerd
  - ttf-jetbrains-mono-nerd
  - papirus-icon-theme
  - breeze-cursors

dotfiles_packages: >-
  {{
    dotfiles_packages_fedora
    if ansible_facts['distribution'] == 'Fedora'
    else dotfiles_packages_arch
    if ansible_facts['distribution'] == 'Archlinux'
    else []
  }}
